# namespace: fastapi-prod
resources:
  - ../../base
  - route.yaml

images:
  - name: quay.io/mukeshs1306/py-fastapi-helloworld
    newTag: latest

commonLabels:
  environment: prod

configMapGenerator:
  - name: fastapi-helloworld-config
    literals:
      - DISPLAY_TEXT="Hello from Production!"
      - IMAGE_PATH="/app/rh-developer.jpg"

generatorOptions:
  disableNameSuffixHash: true