kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fastapi-hello-world-prod

spec:
  subdomain: fastapi-hello-world-prod
  path: /
  to:
    kind: Service
    name: fastapi-helloworld-service
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

